#!/usr/bin/env node
/**
 * Build script. Zero dependencies (Node 18+).
 *
 *   node scripts/build.mjs            build dist/ and docs/
 *   node scripts/build.mjs --check    build in memory, fail if committed output is stale
 *
 * What it does
 *   1. dist/styleguide.css      every file in src/{tokens,base,layout,components,utilities}
 *                               in that order, each wrapped in its own cascade layer
 *   2. dist/styleguide.min.css  the same, comments and whitespace stripped
 *   3. dist/styleguide.js       every file in src/js (plain scripts, no modules, no globals but `SG`)
 *   4. dist/fonts/*             src/fonts copied verbatim (woff2 + licence files)
 *   5. docs/**.html             every docs-src page fragment wrapped in docs-src/_layout.html,
 *                               nav generated from page metadata; docs/assets/ gets dist/ + docs assets
 *
 * Source of truth is always src/ and docs-src/. dist/ and docs/ are generated and committed so
 * that consumers can copy one file, and so GitHub Pages can serve docs/ with no CI.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, existsSync, copyFileSync, rmSync } from 'node:fs'
import { join, dirname, relative, sep, posix, extname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const CHECK = process.argv.includes('--check')
const ALLOW_BROKEN = process.argv.includes('--allow-broken-links') // interim flag while pages are being written
const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))

/**
 * Cascade layers, lowest to highest priority. Each source file opens its own `@layer name { }`
 * block; the build only checks the name is known and emits the ordering statement once at the top.
 * Folders are concatenated in SOURCE_DIRS order (files alphabetically inside a folder).
 */
const SOURCE_DIRS = ['tokens', 'base', 'layout', 'components', 'utilities']
const LAYER_ORDER = 'sg.reset, sg.tokens, sg.base, sg.layout, sg.components, sg.wire, sg.utilities'

/* ------------------------------------------------------------------ helpers */

const out = new Map() // relative path -> Buffer | string
const errors = []
const warn = (m) => console.warn('  ! ' + m)
const fail = (m) => errors.push(m)

function walk(dir, filter = () => true) {
  if (!existsSync(dir)) return []
  const res = []
  for (const name of readdirSync(dir).sort()) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) res.push(...walk(p, filter))
    else if (filter(p)) res.push(p)
  }
  return res
}
const rel = (p) => relative(ROOT, p).split(sep).join('/')
const put = (path, data) => out.set(path, data)

/** Strip block comments without touching strings. Keeps licence banners (comments starting with an exclamation mark). */
function stripComments(css) {
  let res = ''
  for (let i = 0; i < css.length; i++) {
    const c = css[i]
    if (c === '"' || c === "'") {
      const q = c
      res += c
      i++
      while (i < css.length && css[i] !== q) {
        if (css[i] === '\\') res += css[i++]
        res += css[i++]
      }
      res += q
    } else if (c === '/' && css[i + 1] === '*') {
      const end = css.indexOf('*/', i + 2)
      const body = css.slice(i, end + 2)
      if (body.startsWith('/*!')) res += body
      i = end + 1
    } else res += c
  }
  return res
}

/**
 * Conservative minifier: collapses whitespace around structural punctuation only, and never
 * inside a quoted string (so `content: ", "` and quoted data: URIs survive intact). Spaces around
 * + and - are never touched, because calc() needs them. Source rule: quote every url().
 */
function minifyCss(css) {
  const pieces = stripComments(css).split(/("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*')/)
  const min = pieces
    .map((piece, i) => (i % 2 ? piece : piece.replace(/\s+/g, ' ').replace(/\s*([{};,>])\s*/g, '$1').replace(/;}/g, '}')))
    .join('')
  return min.trim()
}

/* --------------------------------------------------------------------- CSS */

function buildCss() {
  const parts = []
  const banner = `/*! ${pkg.name} v${pkg.version} - generated by scripts/build.mjs from src/. Do not edit. */\n`
  parts.push(banner, `@layer ${LAYER_ORDER};\n`)

  for (const dir of SOURCE_DIRS) {
    const files = walk(join(ROOT, 'src', dir), (p) => p.endsWith('.css'))
    for (const file of files) {
      const src = readFileSync(file, 'utf8')
      const name = rel(file)
      // Every rule must live in a layer. Cheap check: a file needs at least one @layer block, and
      // the layer it opens must be one we know about.
      const layers = [...src.matchAll(/@layer\s+([a-z][a-z0-9.-]*)\s*\{/g)].map((m) => m[1])
      const fontFaceOnly = /^\s*(\/\*[\s\S]*?\*\/\s*)*@font-face/.test(src) && layers.length === 0
      if (!layers.length && !fontFaceOnly) fail(`${name}: no "@layer sg.<name> { ... }" block. Every source file must declare its layer.`)
      for (const l of layers) if (!LAYER_ORDER.split(', ').includes(l)) fail(`${name}: unknown layer "${l}". Known: ${LAYER_ORDER}`)
      parts.push(`\n/* ===== ${name} ===== */\n`, src.replace(/\s+$/, '') + '\n')
    }
  }
  const css = parts.join('')
  put('dist/styleguide.css', css)
  put('dist/styleguide.min.css', minifyCss(css) + '\n')
}

/* ------------------------------------------------------------------- wire kit */

/** The owner's wireframe kit (.wf-* placeholders): dev-only, never in the main bundle. */
function buildWire() {
  const files = walk(join(ROOT, 'src', 'wire'), (p) => p.endsWith('.css'))
  if (!files.length) return
  put('dist/wire.css', `/*! ${pkg.name} v${pkg.version} - wireframe kit (.wf-*), dev-only. Generated from src/wire. */\n` + files.map((f) => readFileSync(f, 'utf8')).join('\n'))
}

/* ---------------------------------------------------------------------- JS */

function buildJs() {
  const files = walk(join(ROOT, 'src', 'js'), (p) => p.endsWith('.js'))
  const parts = [`/*! ${pkg.name} v${pkg.version} - generated by scripts/build.mjs from src/js. Do not edit. */\n`, `window.SG = window.SG || {};\n`]
  for (const file of files) {
    const src = readFileSync(file, 'utf8')
    if (/^\s*(import|export)\s/m.test(src)) fail(`${rel(file)}: uses import/export. src/js files are plain IIFE scripts attached to window.SG (no module system, so they work from file://).`)
    parts.push(`\n/* ===== ${rel(file)} ===== */\n`, src.replace(/\s+$/, '') + '\n')
  }
  if (files.length) put('dist/styleguide.js', parts.join(''))
}

/* ------------------------------------------------------------------- fonts */

function copyFonts() {
  for (const file of walk(join(ROOT, 'src', 'fonts'))) put('dist/fonts/' + rel(file).slice('src/fonts/'.length), readFileSync(file))
}


/* ------------------------------------------------------------------- icons */

/**
 * Icons are CSS masks (the owner's system): `<span class="ic ic--name" aria-hidden="true"></span>`.
 * The five the owner drew (arrow, plus, minus, close, check) live in src/base/20-icons.css and ship in the
 * main bundle. Every other src/icons/<id>.svg (24x24 Lucide glyphs, ISC) is re-stroked to the same 2px
 * square-cap weight and emitted into dist/icons.css as .ic--<id>. No sprite, nothing to inline, works from file://.
 */
const CORE_ICONS = new Set(['arrow', 'plus', 'minus', 'close', 'check'])
const ICONS = new Map() // id -> inner svg markup
function loadIcons() {
  for (const file of walk(join(ROOT, 'src', 'icons'), (p) => p.endsWith('.svg'))) {
    const id = posix.basename(rel(file), '.svg')
    const svg = readFileSync(file, 'utf8')
    const m = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/)
    if (!m) { fail(`${rel(file)}: no <svg> element`); continue }
    if (!/viewBox="0 0 24 24"/.test(svg)) fail(`${rel(file)}: icons must use viewBox="0 0 24 24"`)
    ICONS.set(id, m[1].replace(/\s+/g, ' ').replace(/> </g, '><').replace(/"/g, "'").trim())
  }
}
const maskUrl = (inner) =>
  'url("data:image/svg+xml,' +
  encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='#000' stroke-width='2' stroke-linecap='square' stroke-linejoin='miter'>${inner}</svg>`).replace(/'/g, '%27').replace(/%20/g, ' ') +
  '")'
/** Every icon class that exists: the owner's five, their aliases, and the generated set. */
const iconClasses = () => new Set([...CORE_ICONS, 'x', ...ICONS.keys()])

function buildIcons() {
  loadIcons()
  const rules = []
  for (const [id, inner] of [...ICONS].sort(([a], [b]) => a.localeCompare(b))) {
    if (CORE_ICONS.has(id)) continue // the owner's drawings win
    rules.push(`.ic--${id}{--ic:${maskUrl(inner)}}`)
  }
  const css = `/*! ${pkg.name} v${pkg.version} - generated from src/icons by scripts/build.mjs. Do not edit. Lucide (ISC), re-stroked to 2px square caps. */\n@layer sg.base{\n.ic--x{--ic:var(--icon-close)}\n${rules.join('\n')}\n}\n`
  put('dist/icons.css', css)
}

/* -------------------------------------------------------------------- docs */

const GROUP_ORDER = ['Start', 'Foundations', 'Components', 'Patterns', 'Accessibility', 'Project']
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

function parsePage(file) {
  let src = readFileSync(file, 'utf8')
  const m = src.match(/^\s*<!--\s*(\{[\s\S]*?\})\s*-->/)
  if (!m) { fail(`${rel(file)}: first line must be a metadata comment: <!--{"title":"...","group":"Components","order":10,"summary":"..."}-->`); return null }
  let meta
  try { meta = JSON.parse(m[1]) } catch (e) { fail(`${rel(file)}: bad metadata JSON (${e.message})`); return null }
  for (const k of ['title', 'group', 'summary']) if (!meta[k]) fail(`${rel(file)}: metadata needs "${k}"`)
  if (!GROUP_ORDER.includes(meta.group)) fail(`${rel(file)}: unknown group "${meta.group}". Known: ${GROUP_ORDER.join(', ')}`)
  src = src.slice(m[0].length).replace(/^\s+/, '')
  const path = rel(file).slice('docs-src/'.length).replace(/\.html$/, '')
  return { meta, body: src, path, out: path + '.html' }
}

function buildDocs() {
  const layoutFile = join(ROOT, 'docs-src', '_layout.html')
  if (!existsSync(layoutFile)) return
  const layout = readFileSync(layoutFile, 'utf8')
  const pages = walk(join(ROOT, 'docs-src'), (p) => p.endsWith('.html') && !posix.basename(rel(p)).startsWith('_')).map(parsePage).filter(Boolean)

  // Stable order: group order, then `order`, then title.
  pages.sort((a, b) => GROUP_ORDER.indexOf(a.meta.group) - GROUP_ORDER.indexOf(b.meta.group) || (a.meta.order ?? 999) - (b.meta.order ?? 999) || a.meta.title.localeCompare(b.meta.title))

  const seen = new Set()
  for (const p of pages) { if (seen.has(p.out)) fail(`duplicate page ${p.out}`); seen.add(p.out) }

  for (const page of pages) {
    const depth = page.out.split('/').length - 1
    const root = depth ? '../'.repeat(depth) : './'
    const navGroups = GROUP_ORDER.map((g) => {
      const items = pages.filter((p) => p.meta.group === g)
      if (!items.length) return ''
      const lis = items.map((p) => {
        const href = root + p.out
        const current = p === page ? ' aria-current="page"' : ''
        return `<li><a href="${href}"${current}>${esc(p.meta.title)}</a></li>`
      }).join('')
      return `<section class="docs-nav__group"><h2 class="docs-nav__heading">${esc(g)}</h2><ul role="list">${lis}</ul></section>`
    }).join('')

    // Table of contents from <h2 id="..."> in the page body.
    const toc = [...page.body.matchAll(/<h2[^>]*\sid="([^"]+)"[^>]*>([\s\S]*?)<\/h2>/g)]
      .map((m) => `<li><a href="#${m[1]}">${m[2].replace(/<[^>]+>/g, '')}</a></li>`).join('')

    // {{icon-grid}} in a page becomes a grid of every icon in src/icons, generated so it never goes stale.
    if (page.body.includes('{{icon-grid}}')) {
      const grid = `<ul class="icon-grid" role="list">${[...iconClasses()].sort().map((id) => `<li><span class="ic ic--${id}" aria-hidden="true"></span><code>${id}</code></li>`).join('')}</ul>`
      page.body = page.body.replace('{{icon-grid}}', grid)
    }

    let html = layout
      .replaceAll('{{title}}', esc(page.meta.title))
      .replaceAll('{{summary}}', esc(page.meta.summary))
      .replaceAll('{{group}}', esc(page.meta.group))
      .replaceAll('{{root}}', root)
      .replaceAll('{{version}}', esc(pkg.version))
      .replace('{{nav}}', navGroups)
      .replace('{{toc}}', toc ? `<nav class="docs-toc" aria-label="On this page"><h2 class="docs-toc__heading">On this page</h2><ul role="list">${toc}</ul></nav>` : '')
      .replace('{{content}}', page.body)
    // Every icon class a page uses must exist (the typo check the owner's gate calls "every class is defined").
    for (const m of html.matchAll(/\bic--([a-z0-9-]+)/g)) if (!iconClasses().has(m[1])) fail(`${page.out}: uses icon "ic--${m[1]}" but there is no such icon (src/icons/${m[1]}.svg)`)
    if (/\{\{[a-z]+\}\}/.test(html)) fail(`${page.out}: unreplaced template placeholder ${html.match(/\{\{[a-z]+\}\}/)[0]}`)

    // Relative link hygiene: pages may write href="@/components/button" to mean "docs root".
    html = html.replace(/(href|src)="@\/([^"]*)"/g, (_, a, p) => `${a}="${root}${p}"`)
    put('docs/' + page.out, html)
  }


  // ---- Link, anchor and id hygiene across the generated site -------------------------------
  const htmlPages = new Map([...out].filter(([k]) => k.startsWith('docs/') && k.endsWith('.html')).map(([k, v]) => [k.slice(5), String(v)]))
  const idsOf = (html) => [...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1])
  for (const [file, html] of htmlPages) {
    const ids = idsOf(html)
    const dup = ids.filter((id, i) => ids.indexOf(id) !== i)
    // ids inside <symbol> sprites are unique per page by construction; any other duplicate is a bug.
    for (const id of new Set(dup)) fail(`docs/${file}: duplicate id "${id}"`)
    const idSet = new Set(ids)
    for (const m of html.matchAll(/\shref="([^"]+)"/g)) {
      const href = m[1]
      if (/^(https?:|mailto:|tel:|data:|javascript:)/.test(href)) continue
      const [path, frag] = href.split('#')
      let target = file
      if (path) {
        target = posix.normalize(posix.join(posix.dirname(file), path))
        if (target.startsWith('assets/') || !target.endsWith('.html')) continue
        if (!htmlPages.has(target)) {
          (ALLOW_BROKEN ? warn : fail)(`docs/${file}: link to "${href}" does not resolve to a page`)
          continue
        }
      }
      if (frag && !idsOf(htmlPages.get(target)).includes(frag)) (ALLOW_BROKEN ? warn : fail)(`docs/${file}: link "${href}" points to a missing anchor #${frag}`)
    }
  }

  // Docs assets: the library itself (dogfooding) plus docs-only css/js.
  for (const f of ['styleguide.css', 'styleguide.min.css', 'styleguide.js', 'icons.css', 'wire.css']) if (out.has('dist/' + f)) put('docs/assets/' + f, out.get('dist/' + f))
  for (const [k, v] of [...out]) if (k.startsWith('dist/fonts/')) put('docs/assets/' + k.slice('dist/'.length), v)
  for (const f of walk(join(ROOT, 'docs-src', 'assets'))) put('docs/assets/' + rel(f).slice('docs-src/assets/'.length), readFileSync(f))
  // Raw-file marker so GitHub Pages does not run Jekyll over underscores.
  put('docs/.nojekyll', '')
}

/* -------------------------------------------------------------------- main */

console.log(CHECK ? 'Checking generated files are up to date...' : 'Building...')
buildCss()
buildWire()
buildJs()
copyFonts()
buildIcons()
buildDocs()

if (errors.length) {
  console.error('\nBuild failed:\n' + errors.map((e) => '  x ' + e).join('\n'))
  process.exit(1)
}

const managed = (p) => p.startsWith('dist/') || p.startsWith('docs/')
const same = (a, b) => Buffer.compare(Buffer.from(a), Buffer.from(b)) === 0

if (CHECK) {
  const stale = []
  for (const [p, data] of out) {
    const disk = join(ROOT, p)
    if (!existsSync(disk) || !same(readFileSync(disk), data)) stale.push(p)
  }
  for (const dir of ['dist', 'docs']) for (const f of walk(join(ROOT, dir))) if (!out.has(rel(f))) stale.push(rel(f) + ' (orphan: no longer generated)')
  if (stale.length) {
    console.error('\nGenerated files are stale. Run `npm run build` and commit:\n' + stale.map((s) => '  - ' + s).join('\n'))
    process.exit(1)
  }
  console.log(`OK: ${out.size} generated files match.`)
} else {
  // Remove orphans so renamed/deleted sources do not leave dead files behind.
  for (const dir of ['dist', 'docs']) for (const f of walk(join(ROOT, dir))) if (!out.has(rel(f))) rmSync(f)
  let bytes = 0
  for (const [p, data] of out) {
    const disk = join(ROOT, p)
    mkdirSync(dirname(disk), { recursive: true })
    writeFileSync(disk, data)
    bytes += Buffer.byteLength(data)
  }
  const css = out.get('dist/styleguide.css') ?? ''
  const min = out.get('dist/styleguide.min.css') ?? ''
  console.log(`Wrote ${out.size} files (${(bytes / 1024).toFixed(0)} KiB). CSS ${(css.length / 1024).toFixed(1)} KiB, min ${(min.length / 1024).toFixed(1)} KiB.`)
}
